# Generated by Django 4.2.7 on 2024-01-01 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0008_user_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, max_length=1000, null=True, upload_to='images/profile'),
        ),
    ]
