# Generated by Django 4.2.7 on 2023-11-18 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_is_active_product_long_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default=False, max_length=500, upload_to='images/products'),
        ),
    ]
