# Generated by Django 4.2.7 on 2023-12-03 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_productbrand_product_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_information',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_information', to='product.productinformation'),
        ),
    ]
