# Generated by Django 4.2.7 on 2023-12-12 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=200)),
                ('site_url', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=400)),
                ('phone', models.CharField(blank=True, max_length=400, null=True)),
                ('fax', models.CharField(blank=True, max_length=400, null=True)),
                ('email', models.CharField(blank=True, max_length=400, null=True)),
                ('copy_right', models.TextField()),
                ('site_logo', models.ImageField(upload_to='images/site-setting')),
                ('about_us_text', models.TextField()),
                ('is_main_setting', models.BooleanField()),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': '',
            },
        ),
    ]
