# Generated by Django 4.2.7 on 2023-12-15 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0003_alter_slider_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
