# Generated by Django 4.2.7 on 2023-12-15 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0004_slider_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='display_order',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='slider',
            name='url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
