# Generated by Django 4.2.7 on 2023-12-16 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcategory',
            name='url_title',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
