# Generated by Django 4.2.7 on 2023-12-16 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blogcategory_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('slug', models.SlugField(allow_unicode=True, max_length=400)),
                ('image', models.ImageField(max_length=1000, upload_to='images/blogs')),
                ('short_description', models.CharField(max_length=1000)),
                ('text', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('selected_categories', models.ManyToManyField(to='blog.blogcategory')),
            ],
        ),
    ]
