# Generated by Django 4.2.7 on 2023-12-16 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='author',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='author_image',
            field=models.ImageField(blank=True, max_length=1000, null=True, upload_to='images/blogs'),
        ),
    ]
