# Generated by Django 4.2.7 on 2023-12-22 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_blog_crerate_date_alter_blog_author_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='crerate_date',
            new_name='create_date',
        ),
    ]
